name: webdnn-deploy
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6.1
  - numpy
  - pydot
  - pip:
    - jupyter-client
    - ipykernel
    - ipython
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - fileupload
